In [6]:
#su paveldėjimu:
# Sukurkite klasę Vehicle su tokiais atributais - Pavadinimas, Rida
#Sukurkite išvestines klases Car, Bus, Train,
# kurie paveldėtų viską iš Vehicle, ir papildomai būtų galima
# nurodyti Seats - sėdimų vietų skaičių, ir visi 
# turėtų metoda GetSeats() grąžinantį tekstą:
# <Pavadinimas> turi <Seats> sėdimų vietų.
class Vehicle():
    def __init__ (self, P, R):
        self.P = P
        self.R = R

class Car(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt

class Bus(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt
class Train(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt
test = Train (P='Pavadinimas', R= 5000, S = 100)
print(test.GetSeats())

AttributeError: 'Train' object has no attribute 'GetSeats'

In [7]:
# Remigijaus sprendimas
# class Vehicle():
#     def __init__(self, P, R):
#         self.P = P
#         self.R = R
# class Car(Vehicle):
#     def __init__(self, P, R, S):
#        super().__init__(P, R)
#        self.S = S
    
#     def GetSeats(self):
#         Txt = self.P + " turi " + str(self.S) + " sedimu vietu"
#         return Txt
    
# test = Car(P= 'pavadinimas', R=5000, S= 4)
# print(test.GetSeats())
# class Bus(Vehicle):
#     def __init__(self, P, R, S):
#        super().__init__(P, R)
#        self.S = S
    
#     def GetSeats(self):
#         Txt = self.P + "turi " + str(self.S) + " sedimu vietu "
#         return Txt
    
# test = Bus(P= 'pavadinimas', R=5000, S= 4)
# print(test.GetSeats())
# class Train(Vehicle):
#     def __init__(self, P, R, S):
#        super().__init__(P, R)
#        self.S = S
    
#     def GetSeats(self):
#         Txt = self.P + "turi " + str(self.S) + " sedimu vietu"
#         return Txt
    
# test = Train(P= 'pavadinimas', R=5000, S= 4)
# print(test.GetSeats())

pavadinimas turi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu 
pavadinimasturi 4 sedimu vietu


In [ ]:
#parašykite klasę TxtAnalyzer, kuriai kreipimosi metu galima būtų nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, stulpelius skaičių suskirstyti į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, minimalias ir maksimalias vertes. Pythone yra min, max, sum funkcijos


In [10]:
x = [1,2,3,4,5]
x_new = []
for skaičius in x:
    x_new.append(skaičius-0.75)
print(x_new)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [15]:
x = [1,2,3,4,5]
y = [i-0.75 for i in x]
print(y)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [5]:
import numpy as np

In [19]:
# array - masyvai
x = np.arange(0,10, 2)
print(x)
print(type(x))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [20]:
y = x-0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [ ]:
np.average()
np.min()
np.mean()
np.mediana()

In [21]:
a_list = [i for i in range(1, 11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
a_array = np.asarray(a_list) #konvertuoja sąrašą į masyvą
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [23]:
x =  [1,2,3] #sąrašai x ir y
y = [1,4,5]
x_np = np.asarray(x) #konvertuojame sąrašus į masyvus
y_np = np.asarray(y)
c = x_np*y_np
print(c)

[ 1  8 15]


In [27]:
np.min(x)
np.max(y_np)

5

In [29]:
atsitiktinis = np.random.randint(0,10, 100) # atsitiktiniai skaičiai tarp 0 ir 10, kurių sugeneriuos 100 vnt
print(atsitiktinis)

[2 0 2 0 0 3 0 0 7 8 3 6 0 2 5 9 0 3 9 9 6 8 6 8 7 9 0 3 6 8 5 4 3 3 4 1 3
 4 0 4 6 4 7 0 4 7 0 3 0 2 9 6 2 0 7 0 3 1 6 3 9 0 9 2 8 3 4 9 3 5 0 2 8 9
 7 2 9 8 8 4 9 5 6 7 2 1 9 3 9 6 2 4 4 6 6 5 3 5 0 3]


In [30]:
atsitiktinis_float = np.random.rand(100)
print(atsitiktinis_float)

[0.97740585 0.57131621 0.74391095 0.0112413  0.10267282 0.82881737
 0.40988146 0.06631515 0.69739057 0.13440251 0.59627394 0.62605154
 0.01213004 0.36381691 0.11786725 0.47687505 0.87996433 0.09471818
 0.65077026 0.64712985 0.97326517 0.83036092 0.40788058 0.66131566
 0.28463542 0.99815201 0.09140716 0.06325414 0.65423419 0.29052055
 0.72596715 0.67177706 0.28604115 0.93299747 0.99648268 0.39886448
 0.97467029 0.65833299 0.80537149 0.28946542 0.27235775 0.42593366
 0.6594197  0.90052637 0.81803138 0.93929666 0.31816749 0.38177466
 0.38404403 0.15372826 0.03212876 0.38742878 0.2571374  0.41150539
 0.42556567 0.63197138 0.866414   0.99344088 0.68161798 0.79727771
 0.43002765 0.06855883 0.33702658 0.03142285 0.23736946 0.28919638
 0.81494968 0.81463379 0.18229284 0.1598324  0.95631084 0.32545793
 0.78377148 0.97825098 0.27593518 0.93046269 0.95939048 0.25696779
 0.29272982 0.94607201 0.89948517 0.26547678 0.71884684 0.39805658
 0.96376715 0.22936207 0.22780903 0.74671919 0.79815119 0.4688

In [34]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
# mean ir average
vidurkis = np.mean(xas) # mean yra griežtai aritmetinis vidurkis
print(vidurkis)
sv_vidurkis = np.average(xas, weights=svoriai) # average - svorinis vidurkis
print(sv_vidurkis)
# mediana
medx = np.median(xas)
print(medx, np.min(xas), np.max(xas))


5.06
4.841909223441494
5.0 1 9


In [44]:
l = np.linspace(0, 10, 15) # linspace nuo kurio, iki kurio ir kiek skaičių turi būti intervale
print(l)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [46]:
# asarray, arange, min, max, mean, average, median
n_np = np.arange(0,10)
# kaip metodai
minn = n_np.min()
print(minn)
print(n_np.mean())
print(n_np.max())

0
4.5
9


In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

In [6]:
import modulis

NameError: name 'self' is not defined

In [21]:
print(modulis.A)

70


In [68]:
modulis.printA()

Aš esu nauja printA() funkcija
Dar vienas pakeitimas


In [ ]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases į modulį
# patikrinti klasių veikimą
# sukurdami kintamuosius

In [5]:
test = modulis.Car(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())

test = modulis.Bus(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())

test = modulis.Train(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())    

pavadinimas turi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu 
pavadinimasturi 4 sedimu vietu


In [8]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

import modulis
    
kintamasis = modulis.FileAnalyzer('REF_D_1k_FW_2.05.dat')    
kintamasis.readText()
kintamasis.Pmax()
kintamasis.PCE()

[1.2, 1.1766667, 1.1533333, 1.13, 1.1066667, 1.0833333, 1.06, 1.0366667, 1.0133333, 0.99, 0.9666667, 0.9433333, 0.92, 0.8966667, 0.8733333, 0.85, 0.8266667, 0.8033333, 0.78, 0.7566667, 0.7333333, 0.71, 0.6866667, 0.6633333, 0.64, 0.6166667, 0.5933333, 0.57, 0.5466667, 0.5233333, 0.5, 0.4766667, 0.4533333, 0.43, 0.4066667, 0.3833333, 0.36, 0.3366667, 0.3133333, 0.29, 0.2666667, 0.2433333, 0.22, 0.1966667, 0.1733333, 0.15, 0.1266667, 0.1033333, 0.08, 0.0566667, 0.0333333, 0.01, -0.0133333, -0.0366667, -0.06, -0.0833333, -0.1066667, -0.13, -0.1533333, -0.1766667, -0.2]
[0.0016649, 0.0009455, 0.0007314, 0.0005438, 0.0003807, 0.0002361, 0.0001112, 7.9e-06, -8.02e-05, -0.0001565, -0.0002187, -0.0002693, -0.0003116, -0.0003498, -0.0003837, -0.0004108, -0.0004379, -0.000462, -0.0004839, -0.000506, -0.0005252, -0.0005449, -0.000562, -0.0005766, -0.0005938, -0.0006098, -0.0006256, -0.0006376, -0.0006502, -0.0006661, -0.0006754, -0.000687, -0.0006992, -0.0007072, -0.0007168, -0.0007257, -0.000733

2.4974205000000005