In [6]:
#su paveldėjimu:
# Sukurkite klasę Vehicle su tokiais atributais - Pavadinimas, Rida
#Sukurkite išvestines klases Car, Bus, Train,
# kurie paveldėtų viską iš Vehicle, ir papildomai būtų galima
# nurodyti Seats - sėdimų vietų skaičių, ir visi 
# turėtų metoda GetSeats() grąžinantį tekstą:
# <Pavadinimas> turi <Seats> sėdimų vietų.
class Vehicle():
    def __init__ (self, P, R):
        self.P = P
        self.R = R

class Car(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt

class Bus(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt
class Train(Vehicle):
    def __init__ (self, P, R, S):
        super().__init__(P, R) 
        self.S = S   
    def getSeats(self):
        Txt = self.P + "turi" + str(self.S) + "sėdimų vietų"
        return Txt
test = Train (P='Pavadinimas', R= 5000, S = 100)
print(test.GetSeats())

AttributeError: 'Train' object has no attribute 'GetSeats'

In [7]:
# Remigijaus sprendimas
class Vehicle():
    def __init__(self, P, R):
        self.P = P
        self.R = R
class Car(Vehicle):
    def __init__(self, P, R, S):
       super().__init__(P, R)
       self.S = S
    
    def GetSeats(self):
        Txt = self.P + " turi " + str(self.S) + " sedimu vietu"
        return Txt
    
test = Car(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())
class Bus(Vehicle):
    def __init__(self, P, R, S):
       super().__init__(P, R)
       self.S = S
    
    def GetSeats(self):
        Txt = self.P + "turi " + str(self.S) + " sedimu vietu "
        return Txt
    
test = Bus(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())
class Train(Vehicle):
    def __init__(self, P, R, S):
       super().__init__(P, R)
       self.S = S
    
    def GetSeats(self):
        Txt = self.P + "turi " + str(self.S) + " sedimu vietu"
        return Txt
    
test = Train(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())

pavadinimas turi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu 
pavadinimasturi 4 sedimu vietu


In [ ]:
#parašykite klasę TxtAnalyzer, kuriai kreipimosi metu galima būtų nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, stulpelius skaičių suskirstyti į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, minimalias ir maksimalias vertes. Pythone yra min, max, sum funkcijos


In [10]:
x = [1,2,3,4,5]
x_new = []
for skaičius in x:
    x_new.append(skaičius-0.75)
print(x_new)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [15]:
x = [1,2,3,4,5]
y = [i-0.75 for i in x]
print(y)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [16]:
import numpy as np

In [19]:
# array - masyvai
x = np.arange(0,10, 2)
print(x)
print(type(x))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [20]:
y = x-0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [ ]:
np.average()
np.min()
np.mean()
np.mediana()

In [21]:
a_list = [i for i in range(1, 11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
a_array = np.asarray(a_list) #konvertuoja sąrašą į masyvą
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]
